<?php

    $ERROR_USER_DOES_NOT_EXIST = 0;
    $ERROR_USER_ALREADY_EXIST = 1;
    $ERROR_UNKNOWN = 2;
    $ERROR_WRONG_PASSWORD = 3;
    $ERROR_MAIL_NOT_SENT = 4;
    $ERROR_WRONG_CODE = 5;
    $ERROR_SEVERE = 6;
    $ERROR_NOT_SELECTED = 7;
    $ERROR_TECHNICAL_MAIL_NOT_SENT = 8;
    $SUCCESS_LOGIN = 9;
    $SUCCESS_REGISTER = 10;
    $SUCCESS_MAIL = 11;
    $SUCCESS_VERIFICATION = 12;
    $SUCCESS_GIFT = 13;
    $SUCCESS_TECHNICAL_MAIL_SENT = 14;
    $NONE = 15;

    $CODES = array($ERROR_USER_DOES_NOT_EXIST,  $ERROR_USER_ALREADY_EXIST, $ERROR_UNKNOWN, $ERROR_WRONG_PASSWORD, $ERROR_MAIL_NOT_SENT, $ERROR_WRONG_CODE, $ERROR_SEVERE, $ERROR_NOT_SELECTED,$ERROR_TECHNICAL_MAIL_NOT_SENT, $SUCCESS_LOGIN, $SUCCESS_REGISTER, $SUCCESS_MAIL,  $SUCCESS_VERIFICATION, $SUCCESS_GIFT, $SUCCESS_TECHNICAL_MAIL_SENT, $NONE);
    
?>