<?php

    $ERROR_USER_DOES_NOT_EXIST = 0;
    $ERROR_USER_ALREADY_EXIST = 1;
    $ERROR_UNKNOWN = 2;
    $ERROR_WRONG_PASSWORD = 3;
    $ERROR_MAIL_NOT_SENT = 4;
    $ERROR_WRONG_CODE = 5;
    $ERROR_SEVERE = 6;
    $ERROR_NOT_SELECTED = 7;
    $SUCCESS_LOGIN = 8;
    $SUCCESS_REGISTER = 9;
    $SUCCESS_MAIL = 10;
    $SUCCESS_VERIFICATION = 11;
    $SUCCESS_GIFT = 12;
    $NONE = 13;

    $CODES = array($ERROR_USER_DOES_NOT_EXIST,  $ERROR_USER_ALREADY_EXIST, $ERROR_UNKNOWN, $ERROR_WRONG_PASSWORD, $ERROR_MAIL_NOT_SENT, $ERROR_WRONG_CODE, $ERROR_SEVERE, $ERROR_NOT_SELECTED, $SUCCESS_LOGIN, $SUCCESS_REGISTER, $SUCCESS_MAIL,  $SUCCESS_VERIFICATION, $SUCCESS_GIFT, $NONE);
    
?>