<?php

    $ERROR_USER_DOES_NOT_EXIST = 0;
    $ERROR_USER_ALREADY_EXIST = 1;
    $ERROR_QUERY_FAILED = 2;
    $ERROR_WRONG_PASSWORD = 3;
    $SUCCESS_LOGIN = 4;
    $SUCCESS_REGISTER = 5;
    $NONE = 6;

    $CODES = array($ERROR_USER_DOES_NOT_EXIST,  $ERROR_USER_ALREADY_EXIST, $ERROR_QUERY_FAILED, $ERROR_WRONG_PASSWORD, $SUCCESS_LOGIN, $SUCCESS_REGISTER, $NONE);
    
?>